name: Send Release Webhook

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook notification
        env:
          WEBHOOK_URL: ${{ secrets.RELEASE_WEBHOOK_URL }}
        run: node .github/actions/embed.js
