name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js

      - name: Commit bumped manifest
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: bump manifest version to ${{ env.NEW_VERSION }}'

      - name: Create version tag
        run: |
          git tag "v${{ env.NEW_VERSION }}"
          git push origin "v${{ env.NEW_VERSION }}"

      - name: Update latest_production tag
        run: |
          git tag -f latest_production
          git push origin -f latest_production

      - name: Bundle files
        run: |
          mkdir -p ./temp/dirk_lib/web/
          cp ./fxmanifest.lua ./init.lua ./README.md ./LICENSE ./temp/dirk_lib/
          cp -r ./src ./bridge ./locales ./modules ./temp/dirk_lib/
          cp -r ./web/build ./temp/dirk_lib/web/
          cd ./temp && zip -r ../dirk_lib.zip ./dirk_lib

      - name: Create GitHub Release 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.NEW_VERSION }}"
          name: "Release ${{ env.NEW_VERSION }}"
          files: dirk_lib.zip
          draft: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3 
      # - name: Send Discord Webhook
      #   run: node .github/actions/embed.js
      #   env:
      #     WEBHOOK_URL: ${{ secrets.RELEASE_WEBHOOK_URL }}
      #     RELEASE_TAG: v${{ env.NEW_VERSION }}
      #     PREVIOUS_TAG: latest_production
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     IS_PRIVATE_REPO: ${{ github.event.repository.private }}
      #     RELEASE_DESCRIPTION: "New version of dirk_lib released!"
